# Generated by Django 6.0.2 on 2026-02-11 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='print_h',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='product',
            name='print_w',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='product',
            name='print_x',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='product',
            name='print_y',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='product',
            name='template_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_data', models.TextField()),
                ('preview', models.ImageField(blank=True, null=True, upload_to='design_previews/')),
                ('size', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
